include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 🧠 Nomenclatura y convenciones
    camel_case_types: true
    camel_case_extensions: true
    library_prefixes: true
    non_constant_identifier_names: false
    constant_identifier_names: false

    # 🧼 Buenas prácticas
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    avoid_empty_else: true
    unnecessary_this: true
    always_use_package_imports: true
    use_key_in_widget_constructors: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    identifier_name: true

    # 🧩 Organización del código
    sort_constructors_first: true
    directives_ordering: true
    type_annotate_public_apis: true

    # 🎯 Layout y legibilidad
    require_trailing_commas: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_expression_function_bodies: true
    unnecessary_brace_in_string_interps: true
    lines_longer_than_80_chars: false

    # 🔐 Seguridad y robustez
    avoid_dynamic_calls: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
