include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 🧠 Nomenclatura y convenciones
    camel_case_types: true
    camel_case_extensions: true
    library_prefixes: true
    non_constant_identifier_names: true
    constant_identifier_names: false
    identifier_name: true
    file_names: true
    always_specify_types: true

    # 🧼 Buenas prácticas
    avoid_print: true
    avoid_empty_else: true
    avoid_types_on_closure_parameters: true
    avoid_init_to_null: true
    unnecessary_this: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    always_use_package_imports: true
    depend_on_referenced_packages: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_unused_constructor_parameters: true
    avoid_classes_with_only_static_members: true
    use_super_parameters: true

    # 🧩 Organización del código
    sort_constructors_first: true
    directives_ordering: true
    type_annotate_public_apis: true
    unnecessary_lambdas: true
    avoid_positional_boolean_parameters: true
    sort_unnamed_constructors_first: true
    lines_longer_than_80_chars: false

    # 🎯 Legibilidad y layout
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    unnecessary_brace_in_string_interps: true
    avoid_redundant_argument_values: true
    unnecessary_null_checks: true
    avoid_escaping_inner_quotes: true
    avoid_returning_null: true
    avoid_bool_literals_in_conditional_expressions: true
    no_leading_underscores_for_local_identifiers: true
    curly_braces_in_flow_control_structures: true
    sized_box_for_whitespace: true
    unnecessary_overrides: true
    sort_child_properties_last: true
    prefer_typing_uninitialized_variables: true

    # 🔐 Seguridad y robustez
    avoid_dynamic_calls: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    avoid_multiple_declarations_per_line: true
    avoid_relative_lib_imports: true
    invalid_case_patterns: true
