name: animacare_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias principales
  http: ^1.2.1
  get: ^4.6.5
  provider: ^6.1.2
  table_calendar: ^3.0.9
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.1.2
  get_storage: ^2.0.3
  keyboard_avoider: ^0.2.0
  dio: ^5.4.0
  audioplayers: ^5.2.1
  awesome_notifications: ^0.10.1

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo.png
    - assets/sounds/success.mp3
    - assets/sounds/warning.mp3
    - assets/sounds/button.mp3
    - assets/sounds/loading.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
